import { Metadata } from "next"
export const metadata:Metadata = {
  title: {
    absolute:"",
    default:"Ndesks",
    template:"%s | Ndesks dynamic title as template"
  },
  description: 'Generated by Next.js',
}

//title.default -> we use as fallback title for child object
//title.template ->  for dynamic title to add a s prefix or suffix
// title.absolute -> completely ignores default as it is set in Parent usually we dont need that

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:"lightblue",padding:"1rem"}}>Header</header>
        {children}
        
        <footer style={{backgroundColor:"ghostwhite",padding:"1rem"}}><p>Footer</p></footer></body>
    </html>
  )
}
